/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список предстоящих бронирований (§8.7, сценарий С5).
         *     Параметров нет: возвращаются только встречи, которые ещё не начались (§7.9).
         *     Сортировка по startAt по возрастанию.
         */
        get: operations["Bookings_list"];
        put?: never;
        /**
         * @description Создать бронирование (§8.6, сценарий С3).
         *
         *     Порядок проверок (§9.3), первая сработавшая определяет ответ:
         *     1. формат и обязательность полей → 400 validation_error;
         *     2. существование типа события → 404 not_found;
         *     3. выравнивание по сетке и рамки рабочего дня (И6, И7) → 400 validation_error;
         *     4. не в прошлом и в пределах 14-дневного окна → 422 out_of_window;
         *     5. пересечение с существующими бронями (И5), атомарно со вставкой (§5.4) → 409 slot_taken.
         */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список всех типов событий, сортировка по createdAt по возрастанию (§8.2, §7.4). */
        get: operations["EventTypes_list"];
        put?: never;
        /**
         * @description Создать тип события (§8.3, сценарий С4).
         *     Ошибки: 400 validation_error (формат и обязательность, §9.1),
         *     409 event_type_id_taken (И1).
         */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Слоты типа события на всё окно записи: 14 дней, начиная с текущей даты (§8.5, §5.2).
         *     Ответ справочный и может устареть к моменту отправки формы — клиент обязан
         *     обработать 409 при бронировании (§5.4).
         *     Из выдачи исключены слоты с началом в прошлом (Р8); дней вне окна в ответе нет (Р6).
         *     Ошибки: 404 not_found.
         */
        get: operations["EventTypes_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Бронирование — подтверждённая запись гостя на интервал.
         *     После создания не изменяется и не отменяется (Р9).
         */
        Booking: {
            /**
             * Format: uuid
             * @description Идентификатор брони, генерируется системой
             */
            id: string;
            /** @description Тип события */
            eventType: components["schemas"]["BookingEventType"];
            /**
             * Format: date-time
             * @description Начало встречи
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Конец встречи: startAt + durationMinutes типа события на момент создания (И3)
             */
            endAt: string;
            /** @description Имя гостя */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя
             */
            guestEmail: string;
            /** @description Заметка гостя */
            notes?: string;
            /**
             * Format: date-time
             * @description Момент создания, задаётся системой
             */
            createdAt: string;
        };
        /**
         * @description Тело POST /api/bookings (§8.6).
         *     `endAt` клиентом не передаётся: система вычисляет его из длительности типа события (И3).
         */
        BookingCreate: {
            /** @description Ссылка на существующий тип события (И8) */
            eventTypeId: components["schemas"]["EventTypeId"];
            /**
             * Format: date-time
             * @description Начало встречи: выровнено по сетке слотов типа (И6), целиком внутри рабочего дня
             *     09:00–18:00 Europe/Moscow (И7), не в прошлом и в пределах 14-дневного окна (Р6, Р8).
             */
            startAt: string;
            /** @description Имя гостя */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя
             */
            guestEmail: string;
            /** @description Заметка гостя */
            notes?: string;
        };
        /** @description Краткая карточка типа события, встраивается в ответы бронирований (§8.6, §8.7). */
        BookingEventType: {
            id: components["schemas"]["EventTypeId"];
            title: string;
            durationMinutes: components["schemas"]["DurationMinutes"];
        };
        /**
         * @description Слоты одного дня окна записи (§8.5).
         *     Если доступных слотов нет (все в прошлом), день присутствует с пустым `slots` (§5.5).
         */
        DaySlots: {
            /**
             * Format: date
             * @description Дата в таймзоне Europe/Moscow (Р5)
             */
            date: string;
            /**
             * Format: int32
             * @description Число свободных слотов — счётчик «N св.» в календаре (§7.5)
             */
            freeCount: number;
            /** @description Слоты дня со статусами, по времени начала */
            slots: components["schemas"]["Slot"][];
        };
        /**
         * Format: int32
         * @description Длительность встречи в минутах, она же — шаг сетки слотов (Р1, Р2, И2).
         *     Произвольная: целое от 1 до 540 (540 минут — длина рабочего дня 09:00–18:00).
         */
        DurationMinutes: number;
        /**
         * @description Тип события — хранимый шаблон встречи.
         *     После создания не изменяется и не удаляется (§3).
         */
        EventType: {
            /**
             * @description Идентификатор-slug
             * @example meeting-15
             */
            id: components["schemas"]["EventTypeId"];
            /**
             * @description Название встречи
             * @example Встреча 15 минут
             */
            title: string;
            /** @description Описание для карточки в каталоге */
            description: string;
            /** @description Длительность встречи, она же — шаг сетки слотов */
            durationMinutes: components["schemas"]["DurationMinutes"];
            /**
             * Format: date-time
             * @description Момент создания, задаётся системой
             */
            createdAt: string;
        };
        /** @description Тело POST /api/event-types (§8.3). `createdAt` клиентом не передаётся — задаётся системой. */
        EventTypeCreate: {
            /**
             * @description Идентификатор-slug
             * @example intro-call
             */
            id: components["schemas"]["EventTypeId"];
            /**
             * @description Название встречи
             * @example Знакомство
             */
            title: string;
            /** @description Описание */
            description: string;
            /** @description Длительность в минутах: целое от 1 до 540 (Р1) */
            durationMinutes: components["schemas"]["DurationMinutes"];
        };
        /**
         * @description Идентификатор типа события (slug). Задаёт владелец, уникален в системе (И1),
         *     используется в URL. Формат — §9.1.
         */
        EventTypeId: string;
        /** @description 409 event_type_id_taken: тип события с таким id уже создан (И1). */
        EventTypeIdTaken: {
            /** @description Тело ошибки без details (§8.8). */
            error: {
                /**
                 * @description Машиночитаемый код ошибки
                 * @enum {string}
                 */
                code: "event_type_id_taken";
                /** @description Человекочитаемое сообщение */
                message: string;
            };
        };
        /** @description Детализация ошибки валидации по полю (§8.8). */
        FieldError: {
            /** @description Имя поля запроса */
            field: string;
            /** @description Сообщение об ошибке (формулировки — §9.1, §9.2) */
            message: string;
        };
        /** @description 404 not_found: тип события не существует. */
        NotFound: {
            /** @description Тело ошибки без details (§8.8). */
            error: {
                /**
                 * @description Машиночитаемый код ошибки
                 * @enum {string}
                 */
                code: "not_found";
                /** @description Человекочитаемое сообщение */
                message: string;
            };
        };
        /** @description 422 out_of_window: начало брони в прошлом либо вне 14-дневного окна (Р6, Р8). */
        OutOfWindow: {
            /** @description Тело ошибки без details (§8.8). */
            error: {
                /**
                 * @description Машиночитаемый код ошибки
                 * @enum {string}
                 */
                code: "out_of_window";
                /** @description Человекочитаемое сообщение */
                message: string;
            };
        };
        /**
         * @description Слот — интервал [start, end) длиной в длительность типа события.
         *     Вычисляемая структура, в хранилище отсутствует (§4.4).
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота: start + durationMinutes типа события
             */
            end: string;
            status: components["schemas"]["SlotStatus"];
        };
        /**
         * @description Статус слота. Слоты с началом в прошлом и слоты вне окна записи
         *     в выдачу не попадают вовсе — отдельного статуса для них нет (§4.4, §5.1).
         * @enum {string}
         */
        SlotStatus: "free" | "busy";
        /** @description 409 slot_taken: интервал пересекается с существующим бронированием (И5, §5.4). */
        SlotTaken: {
            /** @description Тело ошибки без details (§8.8). */
            error: {
                /**
                 * @description Машиночитаемый код ошибки
                 * @enum {string}
                 */
                code: "slot_taken";
                /** @description Человекочитаемое сообщение */
                message: string;
            };
        };
        /** @description Тело validation_error — единственной ошибки с details (§8.8). */
        ValidationErrorBody: {
            /** @enum {string} */
            code: "validation_error";
            message: string;
            details: components["schemas"]["FieldError"][];
        };
        /** @description 400 validation_error: поля не прошли проверку; время не по сетке (И6) или вне рабочего дня (И7). */
        ValidationFailed: {
            error: components["schemas"]["ValidationErrorBody"];
        };
        /**
         * @description Слоты типа события на всё окно записи: ровно 14 дней, начиная с текущей даты (§5.2, §8.5).
         *     Дней вне окна в ответе нет.
         */
        WindowSlots: {
            /** @description Тип события, для которого построена сетка */
            eventTypeId: components["schemas"]["EventTypeId"];
            /** @description Шаг сетки = длительность типа события (Р2) */
            durationMinutes: components["schemas"]["DurationMinutes"];
            /** @description Дни окна записи по возрастанию даты, первый — текущая дата */
            days: components["schemas"]["DaySlots"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Booking"][];
                    };
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Успешное создание: 201 + конверт `{ data: ... }` (§8). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Booking"];
                    };
                };
            };
            /** @description 400 validation_error: поля не прошли проверку; время не по сетке (И6) или вне рабочего дня (И7). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailed"];
                };
            };
            /** @description 404 not_found: тип события не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description 409 slot_taken: интервал пересекается с существующим бронированием (И5, §5.4). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotTaken"];
                };
            };
            /** @description 422 out_of_window: начало брони в прошлом либо вне 14-дневного окна (Р6, Р8). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutOfWindow"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EventType"][];
                    };
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description Успешное создание: 201 + конверт `{ data: ... }` (§8). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EventType"];
                    };
                };
            };
            /** @description 400 validation_error: поля не прошли проверку; время не по сетке (И6) или вне рабочего дня (И7). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailed"];
                };
            };
            /** @description 409 event_type_id_taken: тип события с таким id уже создан (И1). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeIdTaken"];
                };
            };
        };
    };
    EventTypes_slots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WindowSlots"];
                    };
                };
            };
            /** @description 404 not_found: тип события не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
}
